version: 2
updates:
- package-ecosystem: docker
  directory: /
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  groups:
    docker-minor-patch:
      update-types:
      - minor
      - patch
    docker-major:
      update-types:
      - major
  cooldown:
    default-days: 32 # Slightly over 1 month
